# Generated by Django 3.2 on 2022-05-15 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='image',
            new_name='file',
        ),
    ]
