# Generated by Django 3.2 on 2022-06-09 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_image_files_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='title',
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='%Y:%m:%d'),
        ),
        migrations.AlterField(
            model_name='files',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
